name: ML Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      run: |
        python train.py
        
    - name: "🔢 Architecture Check: Parameters < 20K"
      run: |
        python -c "
        from train import Net
        import torch
        model = Net()
        total_params = sum(p.numel() for p in model.parameters())
        print(f'Total Parameters: {total_params:,}')
        assert total_params < 20000, f'Parameter count {total_params:,} exceeds limit of 20,000'
        "
        
    - name: "🔄 Architecture Check: BatchNorm Present"
      run: |
        python -c "
        from train import Net
        import torch.nn as nn
        model = Net()
        bn_count = sum(1 for m in model.modules() if isinstance(m, nn.BatchNorm2d))
        print(f'BatchNorm Layers Found: {bn_count}')
        assert bn_count > 0, 'Model must include BatchNorm layers'
        "
        
    - name: "🎲 Architecture Check: Dropout Present"
      run: |
        python -c "
        from train import Net
        import torch.nn as nn
        model = Net()
        dropout_count = sum(1 for m in model.modules() if isinstance(m, nn.Dropout))
        print(f'Dropout Layers Found: {dropout_count}')
        assert dropout_count > 0, 'Model must include Dropout layers'
        "
        
    - name: "🔌 Architecture Check: FC Layer Present"
      run: |
        python -c "
        from train import Net
        import torch.nn as nn
        model = Net()
        fc_count = sum(1 for m in model.modules() if isinstance(m, nn.Linear))
        print(f'Fully Connected Layers Found: {fc_count}')
        assert fc_count > 0, 'Model must include Fully Connected layer'
        "
        
    - name: "📊 Performance Check: Accuracy > 99.4%"
      run: |
        pytest test_model.py -v
        
    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: model_*.pth
        retention-days: 5